---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
  - name: pcf-pipelines
  - name: terraform-state

outputs:
  - name: configuration

run:
  path: pcf-pipelines/tasks/tiles/pks/task.sh

params:
  SINGLETON_JOB_AZ:
  DEPLOYMENT_NW_AZS:
  NETWORK_NAME:
  INTERNET_CONNECTED:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  PCF_ERT_DOMAIN:
  CERTS_DOMAIN:
  GCP_PROJECT_ID:
  GCP_VPC_NAME:
  GCP_MASTER_ACCOUNT:
  GCP_WORKER_ACCOUNT: